services:
  test-runner:
    build: .
	volumes:
	  - .:/app
	working_dir: /app
  selenium:
    image: selenium/standalone-chrome:4.41.0
    container_name: selenium-standalone
    shm_size: 2gb
    ports:
      - "4445:4445"
      - "4446:4446"