# Application URL
url = https://www.saucedemo.com/

SeleniumGrid=false
GridURL=http://localhost:4444/wd/hub

# Browser Type
browser = chrome

# Credentials
valid_userName = zQEiwj/H/XeuFAsbhjv4qg==
valid_password = ryArX/hYHhe6yUR9AUIlmA==

#product name
productName = Sauce Labs Backpack

# Implicit Wait
implicitWait = 10

# Explicit Wait
explicitWait = 15

# Login Test Data
expectedHomePageHeading = Products
HomePageHeadingError = FAILED: Home Page heading is not matching!!
invalid_userName = invalid-user
invalid_password = invalid-pwd
expectedInvalidLoginError = Epic sadface: Username and password do not match any user in this service
invalidLoginMissmatchError = FAILED: Invalid login error text is not matching!!
expectedBlankLoginError = Epic sadface: Username is required
BlankLoginMissmatchError = FAILED: Login without credentials error is not matching!!

# Product Details test data
productNameMissmatchError = FAILED: Product name on product details is not as per inventory!!
priceMissmatchError = FAILED: Price o product details is not as per inventory!!
addToCartButtonTextError = FAILED: Button text is not changed to Remove after clicking Add to Cart


